import { darken, rgba } from 'polished';
import { VimeoStyleSettings } from '../../../legacy';
import {
  AstroGranite,
  Porcelain,
  White,
  VimeoBlue,
  VimeoBlueDarkened,
  VimeoBlueLightened,
  Foam,
  Plaster,
  RegentGray,
  RumSwizzle,
  PalePink,
  AshenWinter,
  IronHeart,
} from '../../../color';

const UICOLORS = VimeoStyleSettings.colors.uiColors;

export const ButtonColors = {
  AlternativeBackground: '#3A5161',
  AlternativeBackgroundHover: AstroGranite,
  AlternativeBackgroundActive: darken(0.06, AstroGranite),
  AlternativeOutlineHover: Porcelain,
  DisabledText: '#D0D8DB',
  DisabledBackground: Porcelain,
  LightText: White,
  LightTransparentBackground: rgba(White, 0.3),
  LightTransparentBackgroundActive: rgba(White, 0.7),
  LightTransparentBackgroundHover: rgba(White, 0.5),
  PrimaryBackground: VimeoBlue,
  PrimaryBackgroundActive: darken(0.1, VimeoBlueDarkened),
  PrimaryBackgroundHover: VimeoBlueDarkened,
  PrimaryDarkBackground: VimeoBlue,
  PrimaryDarkBackgroundActive: VimeoBlueDarkened,
  PrimaryDarkBackgroundHover: VimeoBlueLightened,
  PrimaryOutlineHover: Foam,
  PrimaryDisabledText: rgba(White, 0.7),
  PrimaryDisabledBackground: rgba(VimeoBlue, 0.4),
  SecondaryText: AstroGranite,
  SecondaryBackground: Plaster,
  SecondaryBackgroundActive: darken(0.06, Plaster),
  SecondaryBackgroundHover: Porcelain,
  SecondaryDarkBackground: AshenWinter,
  SecondaryDarkBackgroundHover: IronHeart,
  SecondaryDarkBackgroundActive: AshenWinter,
  SecondaryOutlineText: RegentGray,
  SuccessBackground: UICOLORS.successColor,
  SuccessBackgroundActive: darken(0.1, UICOLORS.successColorHover),
  SuccessBackgroundHover: UICOLORS.successColorHover,
  SuccessOutlineHover: RumSwizzle,
  WarningBackground: UICOLORS.alertColor,
  WarningBackgroundActive: darken(0.1, UICOLORS.alertColorHover),
  WarningBackgroundHover: UICOLORS.alertColorHover,
  WarningOutlineHover: PalePink,
  Transparent: rgba(White, 0),
};
