/* DO NOT EDIT THIS FILE AS IT'S GENERATED CODE.
*
* This file provides webpack resolve aliases to the component locations from the data generated by
* react-docs.
*
* This file should be required into the webpack.config and used as the valuse for webpack.resolve.alias
*
* See: http://webpack.github.io/docs/configuration.html#resolve-alias
*
* This file is generated by templates/_package-index.js.template
*/

//Export Global CSS and all components ------------------
exports.paths = {
  'iris/GlobalCSS':'iris/src/globals/css/globals.css',
  'iris/icons':'iris/src/globals/svg/',
  
  'iris/Avatar':'iris/src/components/Avatar/Avatar',
  
  'iris/Badge':'iris/src/components/Badge/Badge',
  
  'iris/Button':'iris/src/components/Button/Button',
  
  'iris/ButtonDialogClose':'iris/src/components/ButtonDialogClose/ButtonDialogClose',
  
  'iris/ButtonIconOnly':'iris/src/components/ButtonIconOnly/ButtonIconOnly',
  
  'iris/CircularButton':'iris/src/components/CircularButton/CircularButton',
  
  'iris/Grid':'iris/src/components/Grid/Grid',
  
  'iris/GridBlock':'iris/src/components/GridBlock/GridBlock',
  
  'iris/GridCol':'iris/src/components/GridCol/GridCol',
  
  'iris/InputCheckbox':'iris/src/components/InputCheckbox/InputCheckbox',
  
  'iris/InputLabel':'iris/src/components/InputLabel/InputLabel',
  
  'iris/InputLabelInline':'iris/src/components/InputLabelInline/InputLabelInline',
  
  'iris/InputMessage':'iris/src/components/InputMessage/InputMessage',
  
  'iris/InputMessageArea':'iris/src/components/InputMessageArea/InputMessageArea',
  
  'iris/InputRadio':'iris/src/components/InputRadio/InputRadio',
  
  'iris/InputRadioSet':'iris/src/components/InputRadioSet/InputRadioSet',
  
  'iris/InputSelect':'iris/src/components/InputSelect/InputSelect',
  
  'iris/InputText':'iris/src/components/InputText/InputText',
  
  'iris/InputToggle':'iris/src/components/InputToggle/InputToggle',
  
  'iris/InputWrapper':'iris/src/components/InputWrapper/InputWrapper',
  
  'iris/InputWrapperInline':'iris/src/components/InputWrapperInline/InputWrapperInline',
  
  'iris/LoaderCircular':'iris/src/components/LoaderCircular/LoaderCircular',
  
  'iris/Modal':'iris/src/components/Modal/Modal',
  
  'iris/Notification':'iris/src/components/Notification/Notification',
  
  'iris/NotificationNeutral':'iris/src/components/NotificationNeutral/NotificationNeutral',
  
  'iris/NotificationSuccess':'iris/src/components/NotificationSuccess/NotificationSuccess',
  
  'iris/NotificationWarning':'iris/src/components/NotificationWarning/NotificationWarning',
  
  'iris/TextArea':'iris/src/components/TextArea/TextArea',
  
};
