/* DO NOT EDIT THIS FILE AS IT'S GENERATED CODE.
*
* This file provides webpack resolve aliases to the component locations from the data generated by
* react-docs.
*
* This file should be required into the webpack.config and used as the valuse for webpack.resolve.alias
*
* See: http://webpack.github.io/docs/configuration.html#resolve-alias
*
* This file is generated by templates/_package-index.js.template
*/

//Export Global CSS and all components ------------------
exports.paths = {
  'iris/GlobalCSS':'iris/src/globals/css/globals.css',
  'iris/icons':'iris/src/globals/svg/',
  
  'iris/Badge':'iris/src/components/Badge/Badge',
  
  'iris/Block':'iris/src/components/Block/Block',
  
  'iris/Button':'iris/src/components/Button/Button',
  
  'iris/Col':'iris/src/components/Col/Col',
  
  'iris/Grid':'iris/src/components/Grid/Grid',
  
};
