/* DO NOT EDIT THIS FILE AS IT'S GENERATED CODE.
*
* This files generates a list of component exports from the data generated by
* react-docs.
*
* This file is used as an export interface for consuming this repo as a NPM Package
*/

// Export all components ------------------


export Badge from "./src/components/Badge/Badge";

export Button from "./src/components/Button/Button";

