const COLORS = {
    VimeoBlue: '#00adef',
    VimeoBlueDarkened: '#0088cc',
    Foam: '#e5f7fd',
    Pistachio: '#7fc400',
    PistachioDarkened: '#5a9e02',
    RumSwizzle: '#f2f9e5',
    SunsetOrange: '#ff4d4d',
    SunsetOrangeDarkened: '#d93636',
    PalePink: '#ffeded',
    AstroGranite: '#1a2e3b',
    RegentGray: '#8699a6',
    SoutherlySky: '#b3bfc8',
    Porcelain: '#e3e8e9',
    Plaster: '#eef1f2',
    Paste: '#f6f7f8',
    White: '#fff',
    WarningYellow: '#ffb21e',
    DarkDark: '#2E2E2E',
};
export default COLORS;
