/* DO NOT EDIT THIS FILE AS IT'S GENERATED CODE.
*
* This files generates a list of component exports from the style data
*/

// Import all documentation ------------------


  export ColorsDocs from "../doc-assets/additional-entries/Colors/Colors-Docs";

  export SvgsDocs from "../doc-assets/additional-entries/Svgs/Svgs-Docs";

  export BadgeDocs from "../src/components/Badge/Badge-Docs";

  export ButtonDocs from "../src/components/Button/Button-Docs";

