name: Publish Prerelease

on:
  workflow_dispatch:
    inputs:
      preId:
        description: 'Prerelease identifier (version-[preId])'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          # Setup .npmrc file to publish to npm
          registry-url: 'https://registry.npmjs.org'
      
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm version prerelease --preid=${{ github.event.inputs.preId }} --no-commit-hooks
      - run: npm publish --tag ${{ github.event.inputs.preId }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_VIMEO_PUBLISH_TOKEN }}
