name: Publish Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          # Setup .npmrc file to publish to npm
          registry-url: 'https://registry.npmjs.org'
      
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_VIMEO_PUBLISH_TOKEN }}
