name: CI (Pull Request)

on:
  pull_request:
    branches:
      - 'main'
      - 'workflows'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - run: pnpm i --frozen-lockfile
      - run: pnpm typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm build

  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm build-storybook

  jest: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm jest

  visual-regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            .pnpm-store
            pnpm
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm i --frozen-lockfile
      - run: pnpm build-storybook

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.4.1
