name: CI

on:
  push:
    branches:
      - main
      - workflows

  pull_request:
    branches:
      - main
      - workflows

jobs:
  typecheck:
    name: 'typecheck'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: yarn install
      - run: yarn typecheck